### ISSUE TITLE
Assignment 1 Ready for grading

### ISSUE THREAD

**Issue by adriana-lh** [SES-5215-F2020/alassoharrier-quant#1]
Hello,
My R markdown file, HTML file, and .csv file have all been uploaded to my repo. 

Thank you!

**Comment by saratepfer** [comment]
Great job.

**Comment on content**
I believe your unit of analysis is household-level data, rather than the 2018 ACS, as you state.

For overall legibility, it may be useful to rename your variables to something other than the original codes. The reader is left to infer which codes correspond to which variables.
