### ISSUE TITLE
Assignment 4 ready for grading

### ISSUE THREAD

**Issue by adriana-lh** [SES-5215-F2020/alassoharrier-quant#4]
Hello, 

Assignment 4 is ready for grading and can be viewed at: https://ses-5215-f2020.github.io/alassoharrier-quant/Assignment-4

**Comment by saratepfer** [comment]
Nice job, Adriana! A few comments, below: 

- line 91: I would use the multiple R squared, rather than the adjusted R squared value. 
- general: is there a reason you left total population out of your regression model?
- line 93: I would be more specific here. I would specify that it is for every one unit change in median age that we observe the estimated change in pct internet access.
- line 95: It's not that the majority white tracts are more _likely_ to have internet access; rather, it is that their percentage of internet access is 0.07 percentage points higher than those with no majority race.
